### PR TITLE
Add tagging/picture support for FLAC

### PR DESCRIPTION
**Pull request by arbingordon**

### CODE REVIEW

**Comment by J05HI** [comment]
@arbingordon 
I'm getting "TypeError: Cannot read property 'new' of undefined in line 858".
What should I do? It's not that easy to understand the tagging logic

**Comment by J05HI** [comment]
@arbingordon 
Must have something to do with the flac binary.
Need I compile this? And how? I'm on Windows :(

**Comment by RandomNinjaAtk** [comment]
@J05HI 

I tried building from his branch earlier and wasn't able to get it to work, but I'm fairly novice at it. When I tried to build it, I did not have node flac-bindings package. So I used this guide to set it up:
https://www.npmjs.com/package/flac-bindings
Pay attention to the windows configuration settings at the bottom.  I was unable to still get it to work, but I really don't know what I'm doing so you may have better luck..

**Comment by J05HI** [comment]
@RandomNinjaAtk 
Yeah need to add it to the package.json and install it then,
But no luck...

**Comment by J05HI** [comment]
Of we can't get it to work we could try this one: [https://github.com/claus/flac-metadata](https://github.com/claus/flac-metadata)
Looks like it doesn't need to compile anything.

**Comment by arbingordon** [comment]
@J05HI the bindings for flac-metadata are incomplete, that's why I ended up having to use this lib.
I think one of the gotcha's I had to deal with to get that to work was to rename libFLAC.dll in %path% to FLAC.dll.
I had a lot of trouble getting that lib to work originally too, maybe try this smaller and more straightforward test script I was using to get a feel for how the lib works?
https://gist.github.com/arbingordon/8c05a17e1f4e5ce4f42a3ef05b3f0a05

And like Ninja said follow these instructions:
npm install --global --production windows-build-tools
npm config set msvs_version 2015 --global
All I did was grab libFLAC.dll out of http://www.rarewares.org/files/lossless/flac_dll-1.3.2-git-20171020-x64.zip

**Comment by J05HI** [comment]
@arbingordon
Yeah really annoying that the author doesn't support all platforms :(

**Comment by arbingordon** [comment]
@J05HI anywhere in %path%.
Are you running on windows?  I'm on windows, just needed to do the aforementioned stuff first beforehand.

**Comment by J05HI** [comment]
@arbingordon 
Now I know what you mean :)
But thats really bad. We can't force the users to do that

**Comment by arbingordon** [comment]
Yea, I don't agree with the flac-binding's author's choice of looking for FLAC.dll over libFLAC.dll.

**Comment by tazitus** [comment]
There's also [ffmetadata](https://www.npmjs.com/package/ffmetadata), which works for both MP3 and FLAC. It just needs ffmpeg or libav installed.

**Comment by arbingordon** [comment]
@tazitus ffmeta doesn't support images for flac.

**Comment by J05HI** [comment]
@tazitus
You need ffmpeg. I would like to use a standalone module without any dependencies.

**Comment by J05HI** [comment]
@arbingordon  @tazitus 
I got it to work with another lib :)
Will commit it if it's complete.

**Comment by RandomNinjaAtk** [comment]
@J05HI 
Looking forward to it!

**Comment by J05HI** [comment]
@arbingordon  @RandomNinjaAtk @arbingordon 

See [https://github.com/J05HI/DeezLoadr/commit/f33659c87a1e6e7bd9acdac75fff88eebb55607b](https://github.com/J05HI/DeezLoadr/commit/f33659c87a1e6e7bd9acdac75fff88eebb55607b)

**Pull request closed without merging**
